# Generated by Django 5.1 on 2024-10-23 17:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_promotion_discount_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('badge_type', models.CharField(choices=[('RECORD_TIME', 'Tiempos record'), ('BEST_RATED', 'Mejor calificado'), ('INTENSE_FIRE', 'Fuego intenso')], max_length=20, verbose_name='Tipo de insignia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('icon', cloudinary.models.CloudinaryField(help_text='Icono de la insignia', max_length=255, verbose_name='image')),
                ('companies', models.ManyToManyField(blank=True, related_name='badges', to='marketplace.company', verbose_name='Empresas')),
            ],
            options={
                'verbose_name': 'Insignia de empresa',
                'verbose_name_plural': 'Insignias de empresas',
                'ordering': ['name'],
            },
        ),
    ]
