# Generated by Django 5.1 on 2024-10-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_companybadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil o página de Facebook', max_length=255, null=True, verbose_name='URL de Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='URL completa de la ubicación en Google Maps', max_length=255, null=True, verbose_name='URL de Google Maps'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de Instagram', max_length=255, null=True, verbose_name='URL de Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='URL completa del enlace de WhatsApp', max_length=255, null=True, verbose_name='URL de WhatsApp'),
        ),
    ]
