# Generated by Django 5.1 on 2024-11-02 06:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingEngine', '0002_alter_agent_options_alter_blockedtime_options_and_more'),
        ('marketplace', '0016_company_facebook_url_company_google_maps_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='company',
            name='whatsapp_url',
        ),
        migrations.AddField(
            model_name='company',
            name='booking_settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='bookingEngine.bookingsettings', verbose_name='Configuración de Reservas'),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen cuadrada para la categoría', max_length=255, null=True, verbose_name='image'),
        ),
    ]
