# Generated by Django 5.1 on 2024-11-02 06:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_remove_company_address_remove_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='marketplace.country', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Foto de portada de la compañía', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil o página de Facebook', max_length=255, null=True, verbose_name='URL de Facebook'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='URL completa de la ubicación en Google Maps', max_length=255, null=True, verbose_name='URL de Google Maps'),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de Instagram', max_length=255, null=True, verbose_name='URL de Instagram'),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='Sin descripción', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen de perfil de la compañía', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='URL completa del enlace de WhatsApp', max_length=255, null=True, verbose_name='URL de WhatsApp'),
        ),
    ]
